global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'log_exporter'
    static_configs:
      - targets: ['log-exporter:8000']

  - job_name: 'anomaly_detector'
    static_configs:
      - targets: ['anomaly-detector:8100']
